spring:
  rabbitmq:
    host: 192.168.0.31
    port: 5674
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10
logging:
  level:
    com.deltav.rabbitmq.listener.RabbitMqConsumerListener: info