spring:
  rabbitmq:
    host: 192.168.0.31
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated # 交换机的确认
    publisher-returns: true # 队列的确认